package com.dji.test.demo.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dji.test.demo.bean.WaypointLineBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WAYPOINT_LINE_BEAN".
*/
public class WaypointLineBeanDao extends AbstractDao<WaypointLineBean, Long> {

    public static final String TABLENAME = "WAYPOINT_LINE_BEAN";

    /**
     * Properties of entity WaypointLineBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LineName = new Property(1, String.class, "lineName", false, "LINE_NAME");
        public final static Property HomeLatitude = new Property(2, String.class, "HomeLatitude", false, "HOME_LATITUDE");
        public final static Property HomeLongitude = new Property(3, String.class, "HomeLongitude", false, "HOME_LONGITUDE");
    }


    public WaypointLineBeanDao(DaoConfig config) {
        super(config);
    }
    
    public WaypointLineBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WAYPOINT_LINE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LINE_NAME\" TEXT NOT NULL ," + // 1: lineName
                "\"HOME_LATITUDE\" TEXT NOT NULL ," + // 2: HomeLatitude
                "\"HOME_LONGITUDE\" TEXT NOT NULL );"); // 3: HomeLongitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WAYPOINT_LINE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WaypointLineBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getLineName());
        stmt.bindString(3, entity.getHomeLatitude());
        stmt.bindString(4, entity.getHomeLongitude());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WaypointLineBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getLineName());
        stmt.bindString(3, entity.getHomeLatitude());
        stmt.bindString(4, entity.getHomeLongitude());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WaypointLineBean readEntity(Cursor cursor, int offset) {
        WaypointLineBean entity = new WaypointLineBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // lineName
            cursor.getString(offset + 2), // HomeLatitude
            cursor.getString(offset + 3) // HomeLongitude
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WaypointLineBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLineName(cursor.getString(offset + 1));
        entity.setHomeLatitude(cursor.getString(offset + 2));
        entity.setHomeLongitude(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WaypointLineBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WaypointLineBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WaypointLineBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
